### ISSUE TITLE
Output layer

### ISSUE THREAD

**Issue by everner-ds** [MRN-Code/Coinstac_VBM_computation#22]
The use cases layer shouldn't know about COINSTAC. No need to make anything in the use case layer give output that matches what you need for COINSTAC output. In this case it's not too bad, but it's usually better to include an output layer outside of your use case. That way your use case doesn't depend on your output format.

https://github.com/MRN-Code/Coinstac_VBM_computation/blob/0f1b9db6567d583d9c4b67ab4664a14c1fbe87ca/vbm_use_cases_layer.py#L361

**Comment by spanta28** [comment]
In the current code, the use cae layer does not depend on the output format, since its only sending the output to run_vbm.py (interface layer), I think this fits with the clean architecture philosophy, correct me if I am wrong. 
I can write a function in run_vbm.py that checks the outputs after use case layer does its thing. But this would be unnecessary may be. Let me know your comment on this and if I need to write a function in interface layer that checks outputs instead of simply having the use case layer send the json output to interface layer.
